In [2]:
import numpy as np
import time

In [3]:
data = list(range(0, 100000));


In [4]:
# here we getr that numpay is more faster then 

py_list=data
start = time.time()
sq = [i**2 for i in py_list]
end = time.time()
print(f"start:{start} and end at:{end} in python {end-start}")

n = np.array(py_list)
start = time.time()
sqq = n**2

end = time.time()

print(f"start:{start} and end at:{end} in numpy {end-start}")

start:1784555190.5452201 and end at:1784555190.5468109 in python 0.001590728759765625
start:1784555190.548682 and end at:1784555190.548842 in numpy 0.00015997886657714844


In [5]:
na = np.array([1,2,3,4,5,6,7])
print(na)

[1 2 3 4 5 6 7]


In [14]:
#all become same data typ e
n2 = np.array([1,2,3,4,5,6,7, "ganesh"])
print(n2, n2.dtype)


['1' '2' '3' '4' '5' '6' '7' 'ganesh'] <U21
<U21


In [15]:
print(n2.shape)

(8,)


In [19]:
n3 = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
print(n3)
print(n3.shape)

[[1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]]
(3, 7)


In [25]:
n4 = np.zeros((3, 4))
print(n4, n4.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)


In [31]:
n5 = np.full((3, 4), 100)
print(n5, n5.shape)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)


In [33]:
n6 = np.eye(3)
print(n6, n6.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [34]:
n7 = np.arange(1, 110)
print(n7)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109]


In [35]:
n8 = np.arange(1, 110, 3)
print(n8)

[  1   4   7  10  13  16  19  22  25  28  31  34  37  40  43  46  49  52
  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100 103 106
 109]


In [38]:
n9 = np.linspace(1, 100, 4)
print(n9)

[  1.  34.  67. 100.]


In [39]:
#properties

In [44]:
arr = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
print(arr.size)
print(arr.ndim)
arr_float = arr.astype(np.float64)
print(arr_float)

21
2
[[1. 2. 3. 4. 5. 6. 7.]
 [1. 2. 3. 4. 5. 6. 7.]
 [1. 2. 3. 4. 5. 6. 7.]]


In [51]:
arr2 = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
arr2_reshape = arr.reshape((7, 3))
print(arr2_reshape, arr2_reshape.shape )


[[1 2 3]
 [4 5 6]
 [7 1 2]
 [3 4 5]
 [6 7 1]
 [2 3 4]
 [5 6 7]] (7, 3)


In [53]:
flattend_arr = arr2.flatten()
print(flattend_arr)

[1 2 3 4 5 6 7 1 2 3 4 5 6 7 1 2 3 4 5 6 7]


In [54]:
print(flattend_arr[0])

1


In [57]:
arr2 = np.array([[1,2,3,4,5,6,7],[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]])
print(arr2[1][1])

2


In [3]:
print(np.round(2.678))    # 3.0
print(np.floor(2.678))    # 2.0
print(np.ceil(2.678))     # 3.0
print(np.trunc(2.678))    # 2.0

3.0
2.0
3.0
2.0


In [4]:
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5])
print(np.abs(arr))     # [1 2 5 3 8 4 2 5]
print(np.sort(arr))    # [-5 -4  1  2  2  3  5  8]
print(np.unique(arr))  # [-5 -4  1  2  3  5  8]

[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]


In [5]:
print(np.square(arr))    # [1, 4, 9, 16, 25]
print(np.sqrt(arr))      # [1, 1.41, 1.73, 2, 2.23]
print(np.pow(arr, 3))    # [1, 8, 27, 64, 125]

[ 1  4 25  9 64 16  4 25]
[1.         1.41421356        nan 1.73205081 2.82842712        nan
 1.41421356 2.23606798]
[   1    8 -125   27  512  -64    8  125]


/var/folders/4b/sf46q5ps12scslknb0bq2m8w0000gn/T/ipykernel_83050/1561311108.py:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(arr))      # [1, 1.41, 1.73, 2, 2.23]


In [6]:
# Mathematical Functions

arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))     # 15
print(np.prod(arr))    # 120
print(np.min(arr))     # 1
print(np.argmin(arr))  # 0
print(np.max(arr))     # 5
print(np.argmax(arr))  # 4
print(np.mean(arr))    # 3.0
print(np.median(arr))  # 3.0
print(np.std(arr))     # 1.41
print(np.var(arr))     # 2.0

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0


In [7]:
# Copy vs View by Slicing
#Sliced list is a copy
py_list = [1, 2, 3, 4, 5]
copy_list = py_list[1:4] #[2, 3, 4]
copy_list[1] = 333

print(copy_list)
print(py_list)

#Sliced array is a view
np_arr = np.array([1, 2, 3, 4, 5])
view_arr = np_arr[1:4] #[2, 3, 4]
view_arr[1] = 333

print(view_arr)
print(np_arr)

#Creating a copy
copy_arr = np_arr[1:4].copy() #[2, 3, 4]
copy_arr[2] = 444
print(copy_arr)
print(np_arr)

[2, 333, 4]
[1, 2, 3, 4, 5]
[  2 333   4]
[  1   2 333   4   5]
[  2 333 444]
[  1   2 333   4   5]
